glasskube/operator

operator/src/main/kotlin/eu/glasskube/kubernetes/api/model/creators.kt
operator/src/main/kotlin/eu/glasskube/operator/Main.kt
operator/src/main/kotlin/eu/glasskube/operator/httpecho/dependent/HttpEchoDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/Matomo.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/MatomoReconciler.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoConfigMap.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoIngress.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoSecret.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoService.kt
operator/src/main/kotlin/eu/glasskube/operator/secrets/SecretGenerator.kt
operator/src/main/kotlin/eu/glasskube/operator/secrets/SecretGeneratorReconciler.kt

15-create base resources for matomo

---

README.md
deploy/base/deployment.yaml
deploy/base/kustomization.yaml
deploy/deploy.sh

Deployment script

---

deploy/deploy.sh

fix: update mariadb-operator repository url (#36)

---

gradle.properties
operator/build.gradle.kts

feat: support pem key authentication for k3s (#44)

---

deploy/crd/httpechos.glasskube.eu-v1.yml
deploy/crd/matomos.glasskube.eu-v1.yml
gradle.properties
operator/src/main/kotlin/eu/glasskube/operator/httpecho/HttpEcho.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/Matomo.kt

feat: rename plural name of Matomo and HttpEcho

---

deploy/cluster/cluster-role.yaml
operator/src/main/kotlin/eu/glasskube/operator/matomo/Matomo.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoIngress.kt

cert manager support via cluster issuer

---

deploy/deploy.sh
operator/src/main/kotlin/eu/glasskube/operator/mariadb/Database.kt
operator/src/main/kotlin/eu/glasskube/operator/mariadb/Grant.kt
operator/src/main/kotlin/eu/glasskube/operator/mariadb/MariaDB.kt
operator/src/main/kotlin/eu/glasskube/operator/mariadb/User.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/mariadb/MatomoDatabaseMariaDB.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/mariadb/MatomoGrantMariaDB.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/mariadb/MatomoUserMariaDB.kt

chore!: upgrade mariadb-operator to version 0.6.1 (#55)

---

deploy/deploy.sh
operator/src/main/kotlin/eu/glasskube/operator/mariadb/Exporter.kt
operator/src/main/kotlin/eu/glasskube/operator/mariadb/MariaDB.kt
operator/src/main/kotlin/eu/glasskube/operator/mariadb/Metrics.kt
operator/src/main/kotlin/eu/glasskube/operator/mariadb/ServiceMonitor.kt
operator/src/main/kotlin/eu/glasskube/operator/mariadb/User.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/mariadb/MatomoMariaDB.kt
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/mariadb/MatomoUserMariaDB.kt
operator/src/main/kotlin/eu/glasskube/operator/odoo/dependent/OdooPostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/postgres/ClusterSpec.kt
operator/src/main/kotlin/eu/glasskube/operator/postgres/MonitoringConfiguration.kt

feat: prometheus persistence and grafana ingress

---

deploy/cluster/cluster-role.yaml
operator/src/main/kotlin/eu/glasskube/kubernetes/client/ext.kt
operator/src/main/kotlin/eu/glasskube/operator/Main.kt
operator/src/main/kotlin/eu/glasskube/operator/config/ConfigGenerator.kt
operator/src/main/kotlin/eu/glasskube/operator/generic/dependant/DependentIngress.kt

feat: dynamic Ingress Class detection (#54)

---

deploy/deploy.sh
operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoConfigMap.kt
operator/src/main/kotlin/eu/glasskube/operator/odoo/dependent/OdooPostgresCluster.kt

feat: make cluster dns name configureable (#65)

---

operator/build.gradle.kts
operator/src/main/kotlin/eu/glasskube/operator/Main.kt
operator/src/main/kotlin/eu/glasskube/operator/ReleaseInfo.kt

feat: add accessing ReleaseInfo at runtime (#40)

---

CONTRIBUTING.md
README.md
deploy/deploy.sh

docs: improve getting started section in README (#70)

---

deploy/base/deployment.yaml

feat: add memory limit and request (#51)

---

gradle.properties
operator/build.gradle.kts
operator/src/main/kotlin/eu/glasskube/operator/Main.kt

Remove josdk annotation processor invocation (#72)

---

operator/src/main/kotlin/eu/glasskube/operator/ReleaseInfo.kt
operator/src/main/kotlin/eu/glasskube/operator/Utils.kt
operator/src/main/kotlin/eu/glasskube/operator/api/reconciler/Context.kt
operator/src/main/kotlin/eu/glasskube/operator/boot/InjectionAwareDependentResourceFactory.kt
operator/src/main/kotlin/eu/glasskube/operator/config/ConfigGenerator.kt
operator/src/main/kotlin/eu/glasskube/operator/gitea/GiteaReconciler.kt
operator/src/main/kotlin/eu/glasskube/operator/gitea/dependent/GiteaIniConfigMap.kt
operator/src/main/kotlin/eu/glasskube/operator/httpecho/HttpEchoReconciler.kt
operator/src/main/kotlin/eu/glasskube/operator/minio/MinioBucketReconciler.kt
operator/src/main/kotlin/eu/glasskube/operator/odoo/dependent/OdooConfigMap.kt
operator/src/main/kotlin/eu/glasskube/operator/odoo/dependent/OdooDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/secrets/SecretGenerator.kt

This change now also includes an upgrade of the Odoo image tag to `16.0.20230317`. Please make sure that tag is available before releasing a new version containing this change.

Odoo:  Protect database manager

---

operator/src/main/kotlin/eu/glasskube/operator/gitea/dependent/GiteaIniConfigMap.kt

With out the service enabled Gitea does not send emails
resolve #100

fix: enable gitea email notify (#100)

---

.github/renovate.json

* Adds initial config for renovate
* Would get active when renovate app is enabled on this repo

ci: add renovate config

---

operator/src/main/kotlin/eu/glasskube/operator/apps/matomo/dependent/MatomoDeployment.kt

**IMPORTANT:** This PR depends on https://github.com/glasskube/images/pull/4

chore(Matomo): update image version to 4.14.2

---

deploy/crd/giteas.glasskube.eu-v1.yml
deploy/crd/gitlabs.glasskube.eu-v1.yml
deploy/crd/matomos.glasskube.eu-v1.yml
deploy/crd/odoos.glasskube.eu-v1.yml
operator/src/main/kotlin/eu/glasskube/operator/apps/gitea/GiteaSpec.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/gitea/dependent/GiteaDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/gitlab/GitlabSpec.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/gitlab/dependent/GitlabDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/matomo/Matomo.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/matomo/dependent/MatomoDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/odoo/Odoo.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/odoo/dependent/OdooDeployment.kt

also: add default resource request for Gitlab
Refs: #51

feat: add resource requirements in app specs (#51)

---

.github/workflows/e2e-tests.yaml
.gitignore
charts/glasskube-operator/Chart.yaml
charts/glasskube-operator/values.yaml
e2e/Makefile
e2e/kuttl/kuttl-test.yaml
e2e/kuttl/test/00-assert.yaml
e2e/kuttl/test/00-install.yaml

* adds the first e2e tests using kuttl

chore: add first e2e tests

---

gradle.properties
operator/build.gradle.kts

Makes https://github.com/glasskube/operator/pull/290 obsolete

fix(deps): remove unnecessary dependencies

---

operator/src/main/kotlin/eu/glasskube/operator/apps/gitea/dependent/GiteaDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/gitea/dependent/GiteaPostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/gitlab/dependent/GitlabDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/gitlab/dependent/GitlabPostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/glitchtip/dependent/GlitchtipDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/glitchtip/dependent/GlitchtipPostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/keycloak/dependent/KeycloakPostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/matomo/dependent/MatomoDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/metabase/dependent/MetabasePostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudPostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/odoo/dependent/OdooDeployment.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/odoo/dependent/OdooPostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/vault/dependent/VaultPostgresCluster.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/vault/dependent/VaultStatefulSet.kt
operator/src/main/kotlin/eu/glasskube/operator/config/ConfigGenerator.kt
operator/src/main/kotlin/eu/glasskube/operator/config/ConfigService.kt
operator/src/main/kotlin/eu/glasskube/operator/generic/dependent/postgres/DependentPostgresCluster.kt

feat: add velero volume backup pod annotations (#285)

---

.github/PULL_REQUEST_TEMPLATE.md

I have read and followed the [contributing guidelines](https://github.com/glasskube/operator/blob/main/CONTRIBUTING.md) for this repository.
My code follows the coding style and standards of this project.
I have tested my changes locally.
I have added or updated necessary documentation (if applicable).
All new and existing tests passed.
My changes have been reviewed by at least one other contributor.
I have updated the README or relevant documentation (if applicable).
I have added proper labels to this PR (e.g., bug, enhancement, documentation, etc.).

docs: create PULL_REQUEST_TEMPLATE.md

---

operator/src/main/kotlin/eu/glasskube/operator/apps/plane/dependent/PlaneBackendConfigMap.kt

related to https://github.com/makeplane/plane/issues/2395

fix(Plane): enable email password login

---

operator/src/main/resources/eu/glasskube/operator/apps/nextcloud/dependent/nginx.conf

done like in https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html#nginx-config
- Closes #562
Please provide screenshots or GIFs that demonstrate the changes if your pull request includes visual updates.
Please provide any additional information that may be helpful in understanding or reviewing this PR.

fix(nextcloud): mjs mime type (#562)

---

deploy/crd/keycloaks.glasskube.eu-v1.yml
operator/src/main/kotlin/eu/glasskube/operator/apps/keycloak/KeycloakSpec.kt
operator/src/main/kotlin/eu/glasskube/operator/apps/keycloak/dependent/KeycloakDeployment.kt

We require all commits in this repository to adhere to the following commit message format.
```
<type>: <description> (#<issue number>)
[optional body]
```
The following `<type>`s are available:
* `fix` (bug fix)
* `feat` (includes new feature)
* `docs` (update to our documentation)
* `build` (update to the build config)
* `perf` (performance improvement)
* `style` (code style change without any other changes)
* `refactor` (code refactoring)
* `chore` (misc. routine tasks; e.g. dependency updates)
This format is based on [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
Please refer to the Conventional Commits specification for more details.
Please describe the changes made in this PR and provide context on why these changes are necessary.
- Closes #issue_number
- …

chore(keycloak): add compatibility options to enable support for Keycloak 25 and 26
