glasskube/operator

operator/src/main/kotlin/eu/glasskube/operator/odoo/dependent/OdooPostgresCluster.kt
resolves #79 
with this change WAL backups only take up a friction of uncompressed backups:
=> feat: compress wal and data backups (#79)

deploy/base/deployment.yaml, operator/build.gradle.kts
resolves #84 
[Spring Boot Docker](https://spring.io/guides/topicals/spring-boot-docker/) uses [Paketo](https://paketo.io/docs/howto/java/) to build java images. Per default during startup paketo configures dynamic memory limits - which are quite high.
There is a [proposal for a low profile mode in the calculator](https://github.com/paketo-buildpacks/rfcs/blob/main/text/java/0007-low-profile-memory-calc.md).
I reduced the default thread count from [50](https://github.com/paketo-buildpacks/spring-boot/blob/0f0ad7752e3c10ba4c94b98670577763b9e11f82/boot/web_application_type.go#L74). As 16 threads should be more than enough for our use case.
More information can be cound here: https://paketo.io/docs/reference/java-reference/#non-heap
=> perf: reduce JVM thread count from 50 to 16 (#84)

README.md, deploy/deploy.sh
Hey there! `mariadb-operator` maintainer here. We have just migrated to a dedicated organization in GitHub and therefore the previous GitHub Pages URLs used in the chart registry will no longer work.
This PR migrates the deployment script and the documentation references to point to the newly created organization:
- https://github.com/mariadb-operator
Also, since DockerHub no longer offers a free tier for organizations, we have also migrated the OCI images to GHCR, see:
- https://github.com/mariadb-operator/mariadb-operator/pkgs/container/mariadb-operator
The [newly released chart](https://artifacthub.io/packages/helm/mariadb-operator/mariadb-operator) defaults to the GHCR images so make sure you update or, alternatively, set an override to your values to point to the GHCR ones.
Thanks …
=> Update mariadb-operator refs to its GitHub organization

deploy/crd/giteas.glasskube.eu-v1.yml, operator/src/main/kotlin/eu/glasskube/operator/gitea/GiteaSmtp.kt, operator/src/main/kotlin/eu/glasskube/operator/gitea/GiteaSpec.kt, operator/src/main/kotlin/eu/glasskube/operator/gitea/dependent/GiteaIniConfigMap.kt
This PR adds optional SMTP support for Gitea instances. SMTP configuration looks like this:
```yaml
spec:
smtp:
host: smtp.example.com
port: 465
fromAddress: gitea@example.com
authSecret:
name: smtp-secret
```
=> feat(Gitea): add support for mailer configuration (#97)

.idea/kotlinc.xml, operator/src/main/kotlin/eu/glasskube/operator/config/ConfigGenerator.kt, operator/src/main/kotlin/eu/glasskube/operator/config/ConfigService.kt, operator/src/main/kotlin/eu/glasskube/operator/config/LabelSubstitutionService.kt, operator/src/main/kotlin/eu/glasskube/operator/generic/dependent/DependentIngress.kt, operator/src/main/kotlin/eu/glasskube/operator/generic/dependent/UpdatableAnnotationsCRUDKubernetesDependentResource.kt, operator/src/main/kotlin/eu/glasskube/operator/gitea/dependent/GiteaIngress.kt, operator/src/main/kotlin/eu/glasskube/operator/gitea/dependent/GiteaSSHService.kt, operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoIngress.kt, operator/src/main/kotlin/eu/glasskube/operator/minio/MinioBucketReconciler.kt, operator/src/main/kotlin/eu/glasskube/operator/odoo/dependent/OdooIngress.kt
This PR introduces new settings items for defining annotations that should be added to all Ingress and LoadBalancer Service resources managed by this operator. To use this new feature, add the following to the `glasskube-settings` `ConfigMap` in the `glasskube-system` namespace:
```yaml
data:
commonLoadBalancerAnnotations: |
hello: world
foo: bar
commonIngressAnnotations: (same as above)
```
Limited support for variable substitution is available. The following substitutions are supported: `${primary.metadata.name}`, `${primary.metadata.namespace}`.
=> Common annotations for Ingress & LoadBalancer Services

operator/src/main/kotlin/eu/glasskube/kubernetes/api/model/Creators.kt, operator/src/main/kotlin/eu/glasskube/operator/gitea/dependent/GiteaDeployment.kt, operator/src/main/kotlin/eu/glasskube/operator/gitea/dependent/GiteaPostgresCluster.kt, operator/src/main/kotlin/eu/glasskube/operator/gitea/dependent/GiteaServiceMonitor.kt, operator/src/main/kotlin/eu/glasskube/operator/odoo/dependent/OdooDeployment.kt, operator/src/main/kotlin/eu/glasskube/operator/odoo/dependent/OdooPostgresCluster.kt
This change reduces the amount of unnecessary updates caused by this default value being set explicitly.
=> fix: change secretKeySelector to discard optional=false

deploy/deploy.sh
BREAKING CHANGE: mariadb-operator does provide an upgrade path due to changed label selectors. If you want to upgrade from a previous version you need remove and reinstall mariadb-operator
=> chore(deps)!: upgrade to latest mariadb-operator

LICENSE
=> chore: remove Glasskube reference from LGPL v3.0 license

operator/src/main/resources/eu/glasskube/operator/apps/gitlab/dependent/gitlab.rb
See: https://docs.gitlab.com/omnibus/troubleshooting.html#nginx-error-could-not-build-server_names_hash-you-should-increase-server_names_hash_bucket_size
=> feat(Gitlab): allow longer host names

operator/src/main/kotlin/eu/glasskube/operator/config/ConfigGenerator.kt, operator/src/main/kotlin/eu/glasskube/operator/config/ConfigService.kt, operator/src/main/kotlin/eu/glasskube/operator/generic/dependent/DependentIngress.kt
This PR enables the use of Gardener ingress for automatic creation of Dnsentries, when the operator is run on a Gardener-based Kubernetes cluster.
=> feat: Enable Gardener ingress annotations for dns (#250)

.idea/vcs.xml, deploy/crd/nextclouds.glasskube.eu-v1.yml, docs/docs/03_crd-reference/nextcloud/index.md, docs/docs/03_crd-reference/nextcloud/oidc.md, operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/NextcloudAppsSpec.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudConfigMap.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
This PR introduces a very simple example how the integration of oidc could be done. Please let me know what you think about having secret data directly in the `Nextcloud` resource and the `Deployment`. This PR is meant as a starting point for discussion and implementation.
=> feat: Add oidc integration example for nextcloud (#252)

deploy/crd/nextclouds.glasskube.eu-v1.yml, operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/NextcloudSpec.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudConfigMap.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt, operator/src/main/resources/eu/glasskube/operator/apps/nextcloud/dependent/zzz-glasskube-php-fpm.conf
=> feat(Nextcloud): make maxChildProcesses configurable via crd (#347)

charts/glasskube-operator/templates/cluster-role.yaml, deploy/cluster/cluster-role.yaml
Additional permissions are needed to delete deployments, services and configmaps in order to perform the plane upgrade of #384
=> fix: add deletion permission to cluster role

operator/src/main/kotlin/eu/glasskube/operator/apps/glitchtip/GlitchtipSpec.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/glitchtip/dependent/GlitchtipIngress.kt
Let the ingress try multiple times if connection is refused from upstream service. 
- Closes #400
=> fix(Glitchtip): avoid http 502 from ingress (#400)

operator/src/main/kotlin/eu/glasskube/operator/apps/gitea/dependent/GiteaIniConfigMap.kt
https://github.com/glasskube/operator/pull/387 implicitly introduced a change in the mailer protocol used if `tlsEnabled` is set to `true`. Previously, Gitea used to select "smtps" by default but now it was changed to "smtp-starttls".
With this change, the protocol is changed back to "smtps", unless the SMTP port is set to 587, in which case it is set to "smtp-starttls".
=> fix(Gitea): change secure mailer protocol to smtps unless port is 587

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json
I added the plugin as a gz file until the upstream pr is merged.
Link to upstream PR: https://github.com/karser/docusaurus-plugin-matomo/pull/6
=> docs: add docusaurus matomo plugin

charts/glasskube-operator/templates/gitlabs.glasskube.eu-v1.yml, deploy/crd/gitlabs.glasskube.eu-v1.yml, operator/src/main/kotlin/eu/glasskube/operator/apps/gitlab/GitlabRegistryStorageSpec.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/gitlab/dependent/GitlabDeployment.kt, operator/src/main/resources/eu/glasskube/operator/apps/gitlab/dependent/gitlab.rb
=> feat(Gitlab): provide more options for registry storage configuration (#447)

operator/src/main/kotlin/eu/glasskube/operator/apps/glitchtip/dependent/GlitchtipVeleroSecret.kt
That commit fixes an infamous error that that the opartor was not able to watch the v1/secrets endpoint
=> fix: typo in GlitchTipVeleroSecret

charts/glasskube-operator/templates/giteas.glasskube.eu-v1.yml, charts/glasskube-operator/templates/gitlabrunners.glasskube.eu-v1.yml, charts/glasskube-operator/templates/gitlabs.glasskube.eu-v1.yml, charts/glasskube-operator/templates/glitchtips.glasskube.eu-v1.yml, charts/glasskube-operator/templates/keycloaks.glasskube.eu-v1.yml, charts/glasskube-operator/templates/matomos.glasskube.eu-v1.yml, charts/glasskube-operator/templates/metabases.glasskube.eu-v1.yml, charts/glasskube-operator/templates/miniobuckets.glasskube.eu-v1.yml, charts/glasskube-operator/templates/nextclouds.glasskube.eu-v1.yml, charts/glasskube-operator/templates/odoos.glasskube.eu-v1.yml, charts/glasskube-operator/templates/planes.glasskube.eu-v1.yml, charts/glasskube-operator/templates/vaults.glasskube.eu-v1.yml, deploy/crd/giteas.glasskube.eu-v1.yml, deploy/crd/gitlabrunners.glasskube.eu-v1.yml, deploy/crd/gitlabs.glasskube.eu-v1.yml, deploy/crd/glitchtips.glasskube.eu-v1.yml, deploy/crd/keycloaks.glasskube.eu-v1.yml, deploy/crd/matomos.glasskube.eu-v1.yml, deploy/crd/metabases.glasskube.eu-v1.yml, deploy/crd/miniobuckets.glasskube.eu-v1.yml, deploy/crd/nextclouds.glasskube.eu-v1.yml, deploy/crd/odoos.glasskube.eu-v1.yml, deploy/crd/planes.glasskube.eu-v1.yml, deploy/crd/vaults.glasskube.eu-v1.yml, operator/src/main/resources/application.yaml
particularly, the CRD generator now sorts properties in a different way (see https://github.com/fabric8io/kubernetes-client/issues/5388). Functionality should be unchanged.
=> chore: additional migrations after JOSDK update

operator/src/main/kotlin/eu/glasskube/operator/apps/odoo/OdooReconciler.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/plane/dependent/PlaneApiService.kt, operator/src/main/kotlin/eu/glasskube/operator/generic/dependent/postgres/DependentPostgresCluster.kt
fixes #468 and also an additional issue with Plane that I discovered.
=> fix: prevent redundant reconciliations

operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudCronJob.kt
If a pod failed it would have restarted immediately which resulted in a DOS of the postgres connections.
=> fix(Nextcloud): add backofflimit, to stop pod spamming

operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudConfigMap.kt
nextcloud enforces that requests come from a trusted source. this trusted source is now set from the spec  and gets reconfigured on every new deployment
=> feat(nextcloud): support host change

deploy/crd/giteas.glasskube.eu-v1.yml, docs/docs/03_crd-reference/gitea.md, operator/src/main/kotlin/eu/glasskube/operator/apps/gitea/GiteaSpec.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/gitea/dependent/GiteaVolume.kt
This PR fixes #509 by introducing a new `storage` property in the `GiteaSpec`.
=> feat(Gitea): add storage size to spec (#509)

docs/docs/03_crd-reference/keycloak.md
This pull request enhances the documentation for the Keycloak Custom Resource Definition (CRD) by incorporating details about custom image functionality. By doing so, it provides users with clear instructions on how to utilize custom Docker images effectively within Keycloak deployments. This documentation update addresses the need for comprehensive guidance, ensuring users can seamlessly integrate custom images into their Keycloak instances, thereby enhancing flexibility and customization options for Keycloak deployments.
fixes #462
=> docs: Extend CRD reference in Keycloak documentation with custom image functionality

operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudConfigMap.kt, operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
* Disable the logreader app to avoid the log iterator error.
* set the maintenance window such that maintenance tasks are done during night.
- Related to #562 
Please provide screenshots or GIFs that demonstrate the changes if your pull request includes visual updates.
Please provide any additional information that may be helpful in understanding or reviewing this PR.
=> fix(nextcloud): set maintenance window and disable logreader

operator/src/main/kotlin/eu/glasskube/operator/apps/matomo/dependent/MatomoConfigSecret.kt
SMTP port 465 is typically used with SSL/TLS, not STARTTLS. In this case Matomo must be configured with encryption mode SSL rather than TLS. 
With this PR, the operator implicitly assumes that SSL should be used if the port is 465 or 2465 has been specified. 
This is a bit of a hack, but I think it should work for most cases and at least it doesn't bring a breaking change.
=> fix(matomo): add simple heuristic to choose smtp encryption mode
